### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by VenTaz** [Zpes/bac-dispatch-hook-communication#1]
Why are you releasing a detected thing ? lol

**Comment by Zpes** [comment]
VenTaz this has never been for badlion client specific moron. It never said that anywhere on the gh?

**Comment by Zpes** [comment]
and we both know  removing your entry out of systembigpool is not a big pool, might just add that to piss you off

**Comment by Zpes** [comment]
PoolBigPageTable  moment

**Comment by VenTaz** [comment]
:)
